name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    tags:
      - "v*"
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout
      uses: actions/checkout@v2
      with:
        run: git checkout master
  
    - name: "publish"
      uses: "PRElias/github-actions@0.0.2"
      with:
        echo: "compilando"

    - name: "upload zip"
      uses: actions/upload-artifact@v2
      with:
       name: nutri.zip
       path: app/nutri.zip
       
    - name: "create release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Versão Beta"
        files: |
          app/nutri.zip
