name: CreatingVersion

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        run: git checkout master
  
    - name: Setup .NET Core
      uses: "actions/setup-dotnet@v1"
      with:
        dotnet-version: 3.1.201
        
    - name: Publishing
      run: dotnet publish -c Release -p:PublishDir=./publish
      
    - name: Checking generated files
      run: ls -R
    
    - name: Installing zip
      run: sudo apt-get install zip unzip -qy
       
    - name: Zipping binaries
      run: ls . './publish' -R && zip -r nutri.zip . './publish'
    
    - name: Checking zip file
      run: ls './publish'
       
    - name: "Creating release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: latest
        prerelease: true
        title: "Versão Beta"
        files: |
          . /publish/nutri.zip
